#!/bin/bash
cwl-runner  spinStaticReport.cwl \
 --sampleID "MSSM-5130-DNA-T-03" \
 --sexChrs "XX" \
 --dateSampleCollected "03/03/2021" \
 --dateSampleSequenced "04/03/2021" 
 --patientName "JANE DOE" \
 --MRN "" \
 --DOB "01/01/1950" \
 --IgClass "Not Given" \
 --LightChainType "Not Given" \
 --RevisedISS "Not Given" \
 --DiseaseStatus "Stable" \
 --drugDetailsRanked "exampleInputs/MM-5130-T-03/drug_details.ranked.prediction_engine.results.tsv" \
 --rxBucketSummary "exampleInputs/MM-5130-T-03/rxbucket_summary.ranked.prediction_engine.results.tsv" \
 --variantSupportSummary "exampleInputs/MM-5130-T-03/variant_summary.ranked.prediction_engine.results.tsv" \
 --treeFile "exampleInputs/MSSM-5130-T-03/sample.summ.json.gz" \
 --zScoreTable "exampleInputs/zscores_mssm.tsv" \
 --cnaFile "exampleInputs/MSSM-5130-T-03/exampleInputs/MM-5130-T-03/cna.prediction_engine.results.tsv" \
 --somFile "exampleInputs/MSSM-5130-T-03/exampleInputs/MM-5130-T-03/somatic_mutation.prediction_engine.results.tsv" \
 --snpFile "exampleInputs/MSSM-5130-T-03/exampleInputs/MM-5130-T-03/germline_snp.prediction_engine.results.tsv" \
 --facetsCNCFResultsFile "exampleInputs/MSSM-5130-T-03/tumor.facets_cncf.txt" \
 --mmPSNPlotListData "refData/mmPSN_survivalCurvePlotList.rds"  \
 --scarFile "exampleInputs/scarScore_latest.tsv" \
 --tmbFile "exampleInputs/tumorMutationBurden_latest.tsv" \
 --gep70File "exampleInputs/gep70scores_latest.tsv" \
 --tumorPurityPloidy "exampleInputs/MSSM-5130-T-03/tumor.facets_output.txt" \
 --geneCoordinateBED "refData/hg38_geneCoordinates_TxDB.tsv"
